version: '2'

services:
    node:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - "./app:/app"
        container_name: node
        env_file: secret.env
